### ISSUE TITLE
Trying to create host and equipment but getting error `unexpected function received s01f14`

### ISSUE THREAD

**Issue by kryptoniancode** [bparzella/secsgem#90]
I have set active to false for host and true to equipment but getting error. Following is code for host and equipment.

I run host.py in one terminal and equipment.py in another but getting this error. What could be changes made so it will work?
```
unexpected function received s01f14
{sessionID:0x0000, stream:01, function:14, pType:0x00, sType:0x00, system:0xfd12909f, requireResponse:False}
```

host.py
```host.py
import secsgem.gem
import code

class SecsGemHost(secsgem.gem.GemHostHandler):
    def __init__(self, address, port, active, session_id, name, custom_connection_handler=None):
        secsgem.gem.GemHostHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)

h = SecsGemHost("127.0.0.1", 5000, False, 0, "host")
h.enable()

code.interact("host object is available as variable 'h', press ctrl-d to stop", local=locals())

h.disable()
```

equipment.py
```equipment.py
import secsgem.gem
import code

class SecsGemEquipment(secsgem.gem.GemEquipmentHandler):
    def __init__(self, address, port, active, session_id, name, custom_connection_handler=None):
        secsgem.gem.GemEquipmentHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)

h = SecsGemEquipment("127.0.0.1", 5000, True, 0, "equipment")
h.enable()

code.interact("equipment object is available as variable 'h', press ctrl-d to stop", local=locals())

h.disable()
```

**Comment by kryptoniancode** [comment]
@bparzella 
Sorry to ping, Can you please tell me how it can be implemented?

**Comment by kryptoniancode** [comment]
@bparzella 
Can a simulator be created using this library?
Host and Equipment?
Can you guide what could be possible solution for above error?
Thanks

**Comment by bparzella** [comment]
This error occurs as both ends send and answer S01F13. One end will receive a S01F14 actually being in the communication state COMMUNICATING due to answering the received S01F13. This is not an error, just the message for the reception of this unexpected message.

FYI: The main branch (and other branches) are under development and are not stable. The api might change without notification. If you want to use a stable version you should use the packages on pipy and/or in the dev_0.1 branch.

I already started a simulator (https://github.com/pysecsgem/simulator), but I am implementing SECS I as my main priority, so it won't get any updates for now.
